Ext.define('GayCanada.model.accounts.Accounts', {
	extend: 'Ext.data.Model',

	fields: [
	    { name: 'account', 			mapping: 'Account' },
    	{ name: 'userid', 			mapping: 'UserID' },  
    	{ name: 'password', 		mapping: 'Password' },
     	'thumbnail',
    	{ name: 'dateentered', 		mapping: 'DateEntered' },
    	{ name: 'lastupdated', 		mapping: 'LastUpdated' },
    	{ name: 'lastseen', 		mapping: 'LastLogin' },
    	{ name: 'firstname',		mapping: 'First_Name' },
    	{ name: 'lastname', 		mapping: 'Last_Name' },  
    	{ name: 'birthdate', 		mapping: 'Birthdate', type: 'date', dateFormat: 'Y-m-d' },
    	{ name: 'email', 			mapping: 'Email' },
    	{ name: 'alternateemail', 	mapping: 'Email_Alternate' },
    	{ name: 'securityquestion', mapping: 'SecurityQuestion' },
    	{ name: 'securityanswer', 	mapping: 'SecurityAnswer' },
    	{ name: 'sex', 				mapping: 'Gender' },
    	{ name: 'address', 			mapping: 'Address' },
    	{ name: 'cityid', 			mapping: 'CityID' },  
    	{ name: 'city', 			mapping: 'City' },
    	{ name: 'region', 			mapping: 'Province' },
    	{ name: 'postalcode', 		mapping: 'Postal_Code' },
    	{ name: 'country', 			mapping: 'Country' },
    	{ name: 'community', 		mapping: 'Community' },
    	{ name: 'timezone', 		mapping: 'Zone' },
    	{ name: 'dst', 				mapping: 'DST' },
    	{ name: 'admin', 			mapping: 'Admin', type: 'int' },
    	{ name: 'permission', 		mapping: 'Permission', type: 'int' },
    	{ name: 'onlinestatus', 	mapping: 'OnlineStatus' },
    	{ name: 'onlinemessage', 	mapping: 'OnlineMessage' },
    	{ name: 'sign', 			mapping: 'Sign' },
    	{ name: 'horoscope', 		mapping: 'Horoscope' },
    	{ name: 'passchanged', 		mapping: 'PassChanged' },
    	{ name: 'service', 			mapping: 'Service' },
    	{ name: 'serviceexpires', 	mapping: 'ServiceExpire' },
    	{ name: 'vacstartdate', 	mapping: 'Vac_Start_Date', type: 'date', dateFormat: 'Y-m-d' },
    	{ name: 'vacenddate', 		mapping: 'Vac_End_Date', type: 'date', dateFormat: 'Y-m-d' },
    	{ name: 'vaccityid', 		mapping: 'Vac_CityID' },
    	{ name: 'vaccity', 			mapping: 'Vac_City' },
    	{ name: 'vacregion', 		mapping: 'Vac_Province' },
    	{ name: 'vaccountry', 		mapping: 'Vac_Country' },
    	'qmBackground'    
	]
});