Ext.define('GayCanada.model.directory.AUS', {
	extend: 'Ext.data.Model',

	fields: [
	    { name: 'recordkey', 		mapping: 'EntryID' },  
   		{ name: 'entryid', 			mapping: 'EntryID' }, 
    	{ name: 'trackingnum', 		mapping: 'Tracking_Number' },
    	{ name: 'action', 			mapping: 'Action' },
    	{ name: 'title', 			mapping: 'Title' },  
    	{ name: 'category1', 		mapping: 'Category_1' },
    	{ name: 'category2', 		mapping: 'Category_2' },
    	{ name: 'street', 			mapping: 'Street' },  
    	{ name: 'cityid', 			mapping: 'CityID' },  
    	{ name: 'city', 			mapping: 'City' },
    	{ name: 'region', 			mapping: 'Province' },
    	{ name: 'postalcode', 		mapping: 'Postal_Code' },
    	{ name: 'country', 			mapping: 'Country' },
    	{ name: 'mailingaddress', 	mapping: 'Mailing_Address' },
    	{ name: 'directions', 		mapping: 'Directions' },
    	{ name: 'phone1', 			mapping: 'Phone_1' },
    	{ name: 'phone2', 			mapping: 'Phone_2' },
    	{ name: 'fax', 				mapping: 'Fax' },
    	{ name: 'tollfree', 		mapping: 'Toll_Free' },
    	{ name: 'contact', 			mapping: 'Contact_Name' },
    	{ name: 'description', 		mapping: 'Description', convert: function(v) { var regX = /\n/g; var replaceString = '<br>\n'; return v.replace(regX, replaceString) } },
    	{ name: 'teaser', 			mapping: 'Teaser' }, 
    	{ name: 'hours', 			mapping: 'Hours' },
    	{ name: 'email1', 			mapping: 'Email_1' },
    	{ name: 'email2', 			mapping: 'Email_2' },
    	{ name: 'website', 			mapping: 'URL' },   
    	{ name: 'views', 			mapping: 'Accesses' },
    	{ name: 'showenhanced', 	mapping: 'Show_Enhanced' },
    	{ name: 'nonprofit', 		mapping: 'Non_Profit' },
    	{ name: 'attributes', 		mapping: 'jsonAttributes' },
    	{ name: 'policies', 		mapping: 'Policies' },
    	{ name: 'paymentmethods', 	mapping: 'paymentMethods' },
    	{ name: 'disabled', 		mapping: 'Disabled' },   
    	{ name: 'expires', 			mapping: 'Enhanced_Expires' },
    	{ name: 'created', 			mapping: 'Date_Created' },
    	{ name: 'updated',			mapping: 'Date_Modified' },
    	{ name: 'supporter', 		mapping: 'Show_Enhanced', convert: function(v) { return v === 'Yes' } },
    	{ name: 'enhanced', 		mapping: 'Show_Enhanced', convert: function(v) { return v === 'Yes' } },
    	{ name: 'ausemail', 		mapping: 'AUS_Email' },
    	{ name: 'invoice', 			mapping: 'Invoice_Number' },
    	{ name: 'created', 			mapping: 'Date_Created' },
    	{ name: 'processed', 		mapping: 'Date_Processed' },
    	{ name: 'paymentmethod', 	mapping: 'Payment_Method' },
    	{ name: 'author', 			mapping: 'Author' },
    	{ name: 'affiliation', 		mapping: 'Affiliation' },
	    { name: 'reason', 			mapping: 'Reason' },
	    { name: 'comments', 		mapping: 'Comments' },
	    { name: 'completed', 		mapping: 'Completed' }
	]
});