Ext.define('GayCanada.model.directory.Entry', {
    extend: 'Ext.data.Model',

    fields: [
       { name: 'recordkey', mapping: 'entryid' },
       { name: 'entryid', mapping: 'entryid' },     
       { name: 'title', mapping: 'title' },  
       { name: 'category1', mapping: 'Category_1' },
       { name: 'category2', mapping: 'Category_2' },
       { name: 'subcategory', mapping: 'SubCategory' },
       { name: 'street', mapping: 'address' },  
       { name: 'cityid', mapping: 'cityid' },  
       { name: 'city', mapping: 'city' },
       { name: 'region', mapping: 'province' },
       { name: 'country', mapping: 'Country' },
       { name: 'address', mapping: 'Street', convert: function(v, r) { return r.atreet ? r.atreet + ', ' + r.city + ', ' + r.province : ''  } },
       { name: 'description', mapping: 'Description', convert: function(v) { var regX = /\n/g; var replaceString = '<br>\n'; return v.replace(regX, replaceString) } },
       { name: 'postalcode', mapping: 'postal_code' },
       { name: 'phone1', mapping: 'phone_1' },
       { name: 'phone2', mapping: 'phone_2' },
       { name: 'fax', mapping: 'fax' },
       { name: 'tollfree', mapping: 'Toll_Free' },
       { name: 'contact', mapping: 'Contact_Name' },
       { name: 'teaser', mapping: 'Teaser' }, 
       { name: 'hours', mapping: 'Hours' },
       { name: 'email1', mapping: 'Email_1' },
       { name: 'email2', mapping: 'Email_2' },
       { name: 'website', mapping: 'URL' },
       { name: 'views', mapping: 'Accesses' },
       { name: 'showenhanced', mapping: 'enhancedlisting' },
       { name: 'nonprofit', mapping: 'Non_Profit' },
       { name: 'attributes', mapping: 'jsonAttributes' },
       { name: 'policies', mapping: 'Policies' },
       { name: 'paymentmethods', mapping: 'paymentMethods' },
       { name: 'disabled', mapping: 'Disabled' },   
       { name: 'expires', mapping: 'Enhanced_Expires' },
       { name: 'created', mapping: 'Date_Created' },
       { name: 'updated', mapping: 'Date_Modified' },
       { name: 'supporter', mapping: 'Show_Enhanced', convert: function(v) { return v === 'Yes' } },
       { name: 'enhanced', mapping: 'Show_Enhanced', convert: function(v) { return v === 'Yes' } }  
    ]
});